from PyQt4 import QtCore, QtGui
from filter import *
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 2, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.comboBox_3.addItem(_fromUtf8(""))       
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.gridLayout.addWidget(self.dateTimeEdit, 4, 1, 1, 2)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 5, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        QtCore.QObject.connect(self.pushButton_2,QtCore.SIGNAL("clicked()"),self.deuxieme_fenetre)
        QtCore.QObject.connect(self.pushButton,QtCore.SIGNAL("clicked()"),self.autre)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GESTION VISITEURS", None))
        #MainWindow.setWindowOpacity(0.8)
        self.label.setText(_translate("MainWindow", "Prenom:", None))
        self.label_2.setText(_translate("MainWindow", "Nom:", None))
        self.label_3.setText(_translate("MainWindow", "Batiment:", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "a", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "b", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "c", None))
        self.label_4.setText(_translate("MainWindow", "Numero Etage:", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "0", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "1", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "2", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "3", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "4", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "5", None))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "6", None))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "7", None))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "8", None))
        self.label_5.setText(_translate("MainWindow", "Motif:", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "depot facture", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "rendez-vous", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "bon de commande", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "courrier", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "signature contrat stage", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "entretient", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "coursier", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "livraison", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "visite perso", None))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "renseignements", None))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "test", None))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "caisse", None))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "restaurant", None))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "reunion", None))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "tiquet resto", None))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "contentieux", None))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "recouvrement", None))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "orange money", None))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "dividende", None))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "intervention", None))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "fournisseur", None))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "partenariat", None))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "autres", None))

        self.label_6.setText(_translate("MainWindow", "Date et Heure:", None))
        self.pushButton.setText(_translate("MainWindow", "Valider", None))
        self.pushButton_2.setText(_translate("MainWindow", "Voir Bilan", None))
        now = QtCore.QDateTime.currentDateTime()
        self.dateTimeEdit.setDateTime(now)


    def deuxieme_fenetre(self):
        self.Dialog = QtGui.QDialog()
        ui = Ui_Dialog()
        ui.setupUi(self.Dialog)
        self.Dialog.show()
        self.Dialog.exec_()

    def autre(self):
        heure = QtCore.QDateTime.currentDateTime()
        prenom = self.lineEdit.text()
        nom = self.lineEdit_2.text()
        combo1 = self.comboBox.currentText()
        combo2 = self.comboBox_2.currentText()
        combo3 = self.comboBox_3.currentText()
        self.db = QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName("securite.db")
        self.db.open()
        self.model = QSqlTableModel()
        self.model.setTable("ving")
        query = QSqlQuery()
        query.prepare("INSERT INTO ving (prenom,nom,batiment,etage,motif,heure) \
        VALUES (?,?,?,?,?,?)")
        query.addBindValue(prenom)
        query.addBindValue(nom)
        query.addBindValue(combo1)
        query.addBindValue(combo2)
        query.addBindValue(combo3)
        query.addBindValue(heure)
        query.exec_()
        self.db.close()
        self.effacer()
    def effacer(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        #self.comboBox.clear()
        #self.comboBox_2.clear()
        #self.comboBox_3.clear()
    


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
